[connection.snowflake]
account = "NRRAFEB.DABW"
user = "DABW_USER"
password = "Dabw_user1"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
